### ISSUE TITLE
AP and PD data

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#1]
As I have been given to understand AP and PD data is in copyright. Therefore not putting it here. Rest all dict data put here.

**Comment by gasyoun** [comment]
> AP and PD data is in copyright

Right. I tried to speak at Pune, but they do not want free access to dictionary.

Actually AP is online for free. https://dsal.uchicago.edu/dictionaries/apte/

Do you think anyone would ever find it here?

**Comment by funderburkjim** [comment]
> Do you think anyone would ever find it here?

We don't want to depend on `Security by anonymity`.  

This repository's solution is to use gitignore to keep the copyrighted data absent.

However 'updateDistinctData.sh'  re-opens the barn door.

Another way would be to make this repository (csl-orig) private.   Since (currently) private repositories are free on Github,  this sounds like a good approach.  What do others say?

**Comment by funderburkjim** [comment]
Another approach could be to have Cologne be the 'origin' for this repository.


@drdhaval2785  Whether the origin is Github or Cologne,  we will need a copy of the repository
on Cologne file system.

We should ask webmaster for new space: scans/csl-orig (8gb) 
The current cloned repository on local machine shows as about 0.5GB.    
We could use the extra space for  large restructuring projects, rather than use pywork.

While we're at it, we may want to also get new space for scans/csl-pywork.

@drdhaval2785  Agree?   If so, I'll go ahead and request from webmaster.

**Comment by gasyoun** [comment]
> Another approach could be to have Cologne be the 'origin' for this repository.

Sounds better.

**Comment by drdhaval2785** [comment]
I insist on github repository being the master.

A (hypothetical future) user can create a pull request and we can merge the correction after review.

We can do one thing.

AP and PD can be kept in one csl-orig-private repository and that repo can be kept private. 

Why send rest of 34 dictionary data into non visibility?

**Comment by gasyoun** [comment]
> Why send rest of 34 dictionary data into non visibility?

Exactly.

**Comment by funderburkjim** [comment]
Question:   For the last 4 comments, I did not receive them in my e-mail.
                   @gasyoun  -- Do you know how to fix ?

**Comment by funderburkjim** [comment]
I like the 34-public repo idea. 

For the time being, let's just ignore the two restricted dictionaries as we prepare for the 2020 editions of the public dictionaries, using csl-orig, csl-pywork, csl-websanlexicon.

**Comment by funderburkjim** [comment]
> I did not receive comments ...

@gasyoun Please ignore.  It is my problem.  I did receive emails on comments.

**Comment by drdhaval2785** [comment]
Reopening this old old issue, because we still do not have csl-orig-private repository for AP and PD.

I am not sure whether there is any github place where these files are residing without being public. 
@funderburkjim It seems that we need to open this private repository, so that corrections in AP and PD are also tracked via git and github.
Making it private would take care of the copyright issue.

**Comment by gasyoun** [comment]
> Reopening this old old issue, because we still do not have csl-orig-private repository for AP and PD.

You have your private paid repository, right?

**Comment by funderburkjim** [comment]
This is handled by a 'headless' git repository at Cologne.
I have sent Dhaval information about how to use.

**Comment by drdhaval2785** [comment]
Right. I have a mail in Jan 2020 regarding the same. Thanks for reminding.
