### ISSUE TITLE
skd: BnASa, BnAsa reversion

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#182]
One of the changes in #169 was to change the headword spelling of BnASa (L=25517, 25518) and BnAsa (L=25519, 25520) to BrASa and BrAsa, respectively.   

This was done primarily so these would match the mw verbs BrAS/BrAs  (to shine).

However, now I think it is better to revert the skd spellings of L=25517-20 to 'Bn..' .

The reasons are:
* the Devanagari looks like 'Bn' , although the 'n' is unusual.
   [Scan page 556, col. 3](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=SKD&page=3-556)
* The alphabetical ordering is preserved with 'Bn' but is broken with 'Br':
   * L=25515  BOmI
   * L=25516  BOrikaH
    * L=25517,18 BnASa
    * L=25519,20 BnAsa
    * L=25521 Byasa
    * L=25522 BraMSaH
* There already are 'BrASa/BrAsa' roots at L=25579/80 and L=25583/84, which are in
    proper alphabetical position. [See page 560, col. 1](https://www.sanskrit-lexicon.uni-koeln.de/scans/csl-apidev/servepdf.php?dict=SKD&page=3-560).

## Open question
It remains a question as to what to think of the 'BnASa/BnAsa' entries of skd.
No such spellings could be found in [kavikalpadruma](https://archive.org/details/KaviKalpadruma/page/n103/mode/2up).

durgAdAsa is mentioned in 25517-20, so maybe that commentary is where the 'Bn' comes from.

**Comment by gasyoun** [comment]
> It remains a question as to what to think of the 'BnASa/BnAsa' entries of skd.

@drdhaval2785 ?

**Comment by drdhaval2785** [comment]
No idea.

**Comment by gasyoun** [comment]
Hope Ushas has a clue.

**Comment by Andhrabharati** [comment]
It is just a print error, nothing more.

We can list out too many out-of-order (alphabetic) in many dictionaries. One need not worry too much that by correcting the error the order is disturbed.

There is no such dhAtu as भ्नाश् or भ्नास् in the Skt. language in any (grammatical) school.

Posting the relevant images from the धातुपाठ  text of मुग्धबोध below-

for भ्नाश् (शान्तवर्गः)
![image](https://user-images.githubusercontent.com/75209130/128602804-438fb68e-0572-47ae-91c0-5f2f22a518f9.png)

for भ्नास् (सान्तवर्गः)
![image](https://user-images.githubusercontent.com/75209130/128602737-efda987a-62d6-4ee6-94ac-475049b076f0.png)

It has nothing to do with the commentaries (दुर्गादास or any other). The basic text itself has these words.

It is not mentioned by Böhtlingk or Palsule in their works (both are stalwarts by any standards, in their resp. times; and one can safely take their works to be fool-proof.)

As I am looking into VCP and SKD seriously, noticed quite many errors of many kinds (including the unnecessary erratic duplicates like this, that confuse the user/reader, which are not recognised even as variants in may a case by any commentator) in both the works. (And this is not a place to list any of them!)

**Comment by drdhaval2785** [comment]
Considering above comment, nothing further is needed. Closing the issue. Current

**Comment by Andhrabharati** [comment]
@drdhaval2785 

Sorry again for posting in a closed issue.

I had rather concluded hastily in saying that 

> It is just a print error, nothing more.

**I was rather heavily believing in Palsule's words and text, in his Kavikalpadruma edition.**

He mentioned that he had used the Jivananda Vidyasagara's and Ashubodha Vidyabhushana's editions of KKD in preparing the critical edition with all variants.

![image](https://user-images.githubusercontent.com/75209130/128663882-69323371-d804-4ed9-931a-bcfbb499b546.png)

And he was saying that he could get hold of Sivanarayana Siromani's edition at a later stage after finishing the collation work, but still he went through it to see if it gives any addl. info.

![image](https://user-images.githubusercontent.com/75209130/128664040-d7bf18ea-f266-4c3b-9e6e-89d180320645.png)


Just to see that no stone is left unturned, I had gone through all these editions, and found that AV & SS editions do have the BnASa, BnAsa variants **very clearly within the commentary portion** under the original text.

@funderburkjim had rightly guessed and said thus-
> durgAdAsa is mentioned in 25517-20, so maybe that commentary is where the 'Bn' comes from.

As both the editions referred above (AV & SS) have the same matter (and in same style), just posting the image from शकारान्त section in Ashubodha Vidyabhushana's edition-

![image](https://user-images.githubusercontent.com/75209130/128665835-dc373c13-86c2-49c1-8a1c-358680e4d3e0.png)

One can find the variant reading towards the bottom of this image, mentioned in a sentence "(भ्राशधातू) रनौ च स्याताम्, रेफस्थाने दन्त्य-नकारो ययोस्तौ रनौ । यथा--" and then lists  भ्नाश्य, भ्नाश as 24th item. 

Similarly the भ्नास्य, भ्नास  are given in the सकारान्त section, listed as 41st item.

![image](https://user-images.githubusercontent.com/75209130/128665674-53ec716c-70a4-4ca2-8639-5b8eb3173b64.png)

Jivananda edition is without a commentary which I had seen first, from which the screenshots were used in my previous post.

**Thus, it looks like Palsule has missed some Bengali variants in his critical edition!**

Now to summarize, we have to have a re-look at the Kavikalpadruma's dhAtu listing; fortunately it seems SKD has captured all these in the revised edition of Basu (वसु) brothers.
[I've looked for a few and the original Radhakantadeva's edition (in Bengali script) is without these variants; also and without the exhaustive vyutpatti portion as in the revised ed., but just with a minimal explanation.]

Coming to @funderburkjim's open question "It remains a question as to what to think of the 'BnASa/BnAsa' entries of skd.", I think we can make an alt. HW field [Cologne addition!] or something similar, and keep the BrASa and BrAsa forms respectively against  the BnASa and BnAsa forms, so that the confusion gets eliminated for ever.

@funderburkjim, @drdhaval2785 & @gasyoun - What is your opinion about this suggestion?

**Comment by Andhrabharati** [comment]
On a 2nd thought, looked all over again at Palsule's book and found him saying thus in the Preface-

![image](https://user-images.githubusercontent.com/75209130/128668073-c5471c78-df66-47b7-86c8-7db834927963.png)

**Thus he might not have paid much attention for the "Eastern Version variants".**

And most probably the नकार  in place of रेफ could be due to scribal error in Bengali copies, as the conjunct form of these two appear almost the same in Devanagari script.

This makes me look for the other region copies with commentaries in devanagari or non-devanagari scripts.

**Comment by Andhrabharati** [comment]
Interesting finding indeed!

The above two AV & SS editions are based on Duragadasa's धातुदीपिका commentary.

I could get hold of Vopadeva's own commentary work काव्यकामधेनु (two different copies) now.
It has a different variant form altogether- भ्ला for भ्रा, as against भ्ना  in धातुदीपिका. 

And in this case, there is no scope for scribal error, as the two characters are entirely different to get confused.

[Where am I going?!!]

**Comment by Andhrabharati** [comment]
Pāṇini has both भ्राश् and भ्लाश् variants in the main धातुपाठ text itself.
