### ISSUE TITLE
Issue dict lnum renaming

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#401]
Ref - https://github.com/sanskrit-lexicon/csl-orig/issues/383#event-3843041588

Recently I saw some issues where Jim had to manually update the dictionary name and L numbers. 

Just wanted to check whether there is something wrong with the code which uploads the github issues ?

**Comment by funderburkjim** [comment]
Sometimes people put the wrong thing in the L-number field of the correction response form.  Nothing wrong with the
upload program on this front.

However,  The program does need to be changed so that it uses token authorization rather than user account authorization.
Each time I use it,  I get a deprecation notice from Github.  In a month or so, the user-account-authorization will stop working.

**Comment by gasyoun** [comment]
> In a month or so, the user-account-authorization will stop working.

But no clue how to fix that? So, so, so good to see you back.
