### ISSUE TITLE
MW: Panini references

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#519]
Several corrections to details of link-specifics of Panini references in mw.
These are errors in tags `<ls>Pāṇ....</ls>`.

These identified in course of working on https://github.com/sanskrit-lexicon/csl-websanlexicon/issues/22.

**Comment by gasyoun** [comment]
Bug? In `nirvaṇa`

nir—vaṇe ind. in the open country, Pāṇ. 6-2, 178; 8-4, 5; Kāś.  [ID=107261]

`Pāṇ. 6-2, 178` link where it should. But `8-4, 5` should not link to the same place, I guess.

**Comment by funderburkjim** [comment]
nirvaRe example:  We would need to make mw.txt differ from the printed text in order
to get two references.

![image](https://user-images.githubusercontent.com/6393033/114288473-3ef7a900-9a3e-11eb-9325-9bbd2d96e705.png)

```
CURRENT:
<s>nir—vaRe</s> ¦ <lex>ind.</lex> in the open country, 
<ls>Pāṇ. 6-2, 178; 8-4, 5</ls>; 
<ls>Kāś.</ls><info lex="ind"/>

TO GET BOTH LINKS, change to two LS tags.  Notice that 'Pāṇ.' appears twice
<ls>Pāṇ. 6-2, 178</ls>; <ls>Pāṇ. 8-4, 5</ls>; 

```

Do we want to make this print change?

**Comment by funderburkjim** [comment]
> Sch. is not really part of Pāṇ. 2-1, 55

```
Current markup:
<ls>Pāṇ. 2-1, 55 <ab>Sch.</ab></ls>

Possible markup change:
<ls>Pāṇ. 2-1, 55</ls> <ab>Sch.</ab>
```

This phenomenon occurs quite often (1575 times).

Should this change be made?

**Comment by gasyoun** [comment]
> Do we want to make this print change?

No, but we want to have that functionality by adding the data to the <ls> tag. 

> This phenomenon occurs quite often (1575 times).

Indeed.

> Should this change be made?

I guess yes, because it's about a commentator on Panini, not Panini himself that is meant. So
`<ls>Pāṇ. 2-1, 55</ls> <ab>Sch.</ab>` @drdhaval2785, right?

**Comment by funderburkjim** [comment]
Moving `<ab>Sch.</ab>` outside of  `<ls>Pāṇ. ...` looks like a better markup.

Let's decide to do the changes to mw.txt.

Although I could assign myself to do this, let's take it as an example where someone else does the work on mw.txt;  I'll then review and do the installation at Cologne.

**Comment by funderburkjim** [comment]
@gasyoun 

To simplify your task,   I've made a temporary repository containing current mw.txt
digitization:  https://github.com/sanskrit-lexicon/temp_corrections_mw

You can:
* Clone this repository
* edit mw.txt  and make the changes in whatever you find the most convenient way, e.g. using emeditor
* When you're satisfied with changes, push the repository back to Github
* and notify me.

Then, I'll do what is necessary to install the changes.

**Comment by gasyoun** [comment]
> Although I could assign myself to do this, let's take it as an example where someone else does the work on mw.txt; I'll then review and do the installation at Cologne.

Agree, let me learn the lesson. So in that step I would only move <ab>Sch.</ab> out, right?

**Comment by funderburkjim** [comment]
Right.  `<ls>Pāṇ. 2-1, 55</ls> <ab>Sch.</ab>` is the final form.

**Comment by funderburkjim** [comment]
Have made the global text change:
`  <ab>Sch.</ab></ls> → </ls> <ab>Sch.</ab>`

4923 instances changed.

@gasyoun Sorry you weren't able to get to this.  Didn't want to wait longer.  Maybe next time.

See commit 50a13d9.

**Comment by funderburkjim** [comment]
Found 15 additional cases with `<ab>Sch` embedded in `<ls>...</ls>`.
Generated changes for this per 
[changes_ls_sch.txt](https://github.com/sanskrit-lexicon/csl-orig/files/6468785/changes_ls_sch.txt)

See commit 3088e75 above.

**Comment by gasyoun** [comment]
> Sorry you weren't able to get to this. Didn't want to wait longer. Maybe next time.

Hectic was the time, lost my granny and aunt, sorry for the long wait without no result.

**Comment by Andhrabharati** [comment]
Of late I was not looking at MW,

Having got this issue notified in my mail box just now, just browsed through it once.

> TO GET BOTH LINKS, change to two LS tags.  Notice that 'Pāṇ.' appears twice
> <ls>Pāṇ. 6-2, 178</ls>; <ls>Pāṇ. 8-4, 5</ls>; 
> 
> Do we want to make this print change?

**No, please don't correct the print matter thus.**
 Instead you can go the <ls n="RV."> as done in PWG to get a different link.
And this case is about ';' between two citations. there are many cases with 'and' between two citations, which could/should also be treated similarly.
`-----------`
I had earlier commented about Panini references with Indo-arabic adhyāya nos. instead of Roman nos. as being one of major "blunders" in MW text, and asked for correcting the same. It is still lying thus without correction.
`-----------`
BTW, happened to see this in the process,
अक्षराङ्ग n. part of a syllable (said of the anusvāra), RV. ; Prāt.  [ID=619]

There is no semi-colon between RV. and Prāt. in the print. This is the similar case of unnecessary splitting of  RV. and Prāt. that I had reported in PWG recently. All such ones are to be corrected in all the texts.

**Comment by Andhrabharati** [comment]
> I had earlier commented about Panini references with Indo-arabic adhyāya nos. instead of Roman nos. as being one of major "blunders" in MW text, and asked for correcting the same. It is still lying thus without correction.

I presume that @funderburkjim had reopened this issue looking at my above posting text.

Here are my earlier posts in this regard-
> This is exactly the one about which I was crying out, from the day I joined Cologne team.
item (c) in sanskrit-lexicon/MWS#95 (comment)
[Our policy at AB is to be close, as much possible, to the print text; except when there is a error/mistake in it- I had mentioned this in one of my posts earlier.]

https://github.com/sanskrit-lexicon/csl-websanlexicon/issues/22#issuecomment-894604665 (7th August 2021)

and
> (c) Pāṇ. is the largest deviant, having changed these (either unwittingly or deliberately) to Indo-Arabic numerals [0-9] (and followed by a dash or erroneously marked/tagged) in the Koeln data! All these can be by found by "Pāṇ. ([0-9])" & "(.?)[0-9]-(.*)</l" and appropriately corrected : over 8000 occurrences.

https://github.com/sanskrit-lexicon/MWS/issues/95#issue-778886883 (5th Jan 2021)

Incidentally there still are some places where this change did not take place yet (fortunate enough to skip the attention of the person at that "bad instant" of the change).

Some very simple ones (very adjacent to Pāṇ.) are -
`<ls>Pāṇ.</ls> (<ls>ii 4, 61</ls>`
`<ls>Pāṇ.</ls> (<ls>iii, 1, 134</ls>`
`<ls>Pāṇ.</ls> (<ls>v, 1, 64</ls>`
`<ls>Pāṇ.</ls> (<ls>v, 2, 62</ls>`
`<ls>Pāṇ.</ls> (<ls>v,2, 36</ls>`
`<ls>Pāṇ.</ls> Vii, 1, 59 <ls>Kāś.</ls>; <ab>ind.p.</ab> <s>गुफित्वा</s>, <ls>i, 2, 23</ls>`
`<ls>Pāṇ.</ls>(<ls>iv, 4, 34</ls>`
`<ls>Pāṇ.</ls>; <ls>ib., ii, 2, 3</ls>`


There are 57 more places (little distant to Pāṇ.)-
`<ls>Pāṇ. 1-1, 1</ls>, <ab>Vārtt.</ab> 12 and 7, <ab>Vārtt.</ab> 1; on <ls>ii, vi, viii</ls>`
`<ls>Pāṇ. 1-3, 87</ls> <ab>Sch.</ab>; <ab>aor.</ab> <s>आशिशत्</s>, <ls>ib. i, 1, 59</ls>`
`<ls>Pāṇ. 1-4, 2</ls>; <s>°धेन</s>, in consequence of a conflict of two rules, iv, 1, 170 <ab>Vārtt.</ab> 1; <s>पूर्व-विप्रतिषेध</s>, a conflict of two rules of which the former prohibits the latter, iv, 2, 39 <ab>Vārtt.</ab> 1; <s>पर-व्°</s>, a conflict of two rules of which the latter prohibits the former, <ls>ii, 2, 35</ls>`
`<ls>Pāṇ. 1-4, 4</ls>]; in <s1 slp1="pARini">Pāṇini</s1>'s grammar the <ab>gen.</ab> case is often used alone, when the word <s>स्थाने</s> has to be supplied <ab>e.g.</ab> <s>हन्तेर् जः</s>, ‘<s>ज</s> is to be substituted in place of <s>हन्</s>’, <ls>i, 1, 49</ls>`
`<ls>Pāṇ. 1-4, 88</ls>; <ls>Kāś.</ls> (often repeated, <ls>ib. viii, 1, 5</ls>`
`<ls>Pāṇ. 1-4, 90</ls>; also at the beginning of a <ab>comp.</ab> <lex type="hwinfo">mfn.</lex>; <ab>cf.</ab> <ls>ib. ii, 2, 18</ls>`
`<ls>Pāṇ. 2-1, 39</ls> <ab>Sch.</ab> & <ls>vi, 3, 2,</ls>`
`<ls>Pāṇ. 2-2, 35</ls>, <ab>Vārtt.</ab> 2; <ab>ifc.</ab> also = pleasant, agreeable <ab>e.g.</ab> <s>गमन-प्रिय</s>, ‘pleasant to go’, <ls>vi, 2, 15</ls>`
`<ls>Pāṇ. 2-3, 29</ls>), <ls>v, 3, 37.</ls>`
`<ls>Pāṇ. 2-3, 34</ls>; <s>°टादागतः</s>, come from afar, <ls>ib. ii, 1, 39</ls>`
`<ls>Pāṇ. 2-3, 69</ls>; <ab>cf.</ab> <ls>iii, 2, 124</ls>`
`<ls>Pāṇ. 2-4, 78; 3-1, 49</ls>; <ab>Prec.</ab> <s>धेयात्</s>, <ls>vi, 4, 67</ls>`
`<ls>Pāṇ. 2-4, 78</ls>; <ab>Prec.</ab> <s>देयात्</s>, <ls>vi, 4, 67</ls>`
`<ls>Pāṇ. 3-1, 129</ls> (<ab>cf.</ab> <ls>vi, 2, 122</ls>`
`<ls>Pāṇ. 3-1, 21</ls>; <ab>ifc.</ab> <ab>g.</ab> <s>चूर्णा<srs/>दि</s>) dust, <ls>iii, 1, 21</ls>`
`<ls>Pāṇ. 3-1, 58</ls>; in derivatives <s>क्</s> for <s>च्</s>, <ls>vii, 3, 59</ls>`
`<ls>Pāṇ. 3-2, 61 and</ls> <s>अग्र-णी</s>, <s>अग्रेणी</s>; but also alone <ab>cf.</ab> <ls>vi, 4, 77; 82</ls>`
`<ls>Pāṇ. 3-3, 58</ls>; <ab>g.</ab> <s>वृषा<srs/>दि</s>) <ab>ifc.</ab> (<ls>iii, 2, 9</ls>`
`<ls>Pāṇ. 4-1, 34</ls>, <ab>Vārtt.</ab> 1, <ls>Pat.</ls>), iv, 19, 7 and (<s>द/ंसु-प/त्°</s>), <ls>vi, 3, 7.</ls>`
`<ls>Pāṇ. 4-1, 52</ls>, <ab>Vārtt.</ab> 1)n.</lex> (<ls>vi, 2, 171</ls>`
`<ls>Pāṇ. 4-1, 95</ls> <ab>patr.</ab> <ab>fr.</ab> <s>पाणिन</s>) <ab>N.</ab> of the most eminent of all native <ns>Sanskṛt</ns> grammarians (he was the author of the <s>अष्टा<srs/>ध्यायी</s> and supposed author of <ab>sev.</ab> other works, <ab>viz.</ab> the <s1 slp1="DAtu-pAWa">Dhātu-pāṭha</s1>, <s1 slp1="gaRa-pATa">Gaṇa-pātha</s1>, <s1 slp1="liNgAnuSAsana">Liṅgânuśāsana</s1> and <s1 slp1="SikzA">Śikṣā</s1>; he was a <s1 slp1="gAnDAra">Gāndhāra</s1> and a native of <s1 slp1="SalAtura">Śalātura</s1>, situated in the North-West near Attok and Peshawar [see, <ls>iv, 3, 94</ls>`
`<ls>Pāṇ. 4-2, 106 and 104</ls>, <ab>Vārtt.</ab> 2; <ab>ifc.</ab> <lex type="hwifc">ind.</lex>, for accent <ab>cf.</ab> <ls>vi, 2, 121</ls>`
`<ls>Pāṇ. 4-3, 120</ls>, <ab>Comm.</ab>; <ls>v, 4, 37</ls>`
`<ls>Pāṇ. 5-1, 33</ls>, <ab>Vārtt.</ab> 1) sown with a <s1 slp1="KAri">Khāri</s1> of grain, <ls>v, 1, 45</ls>`
`<ls>Pāṇ. 5-2, 54</ls>; decl, <ls>i, 1, 36</ls>`
`<ls>Pāṇ. 5-2, 55</ls>; See also, <ls>vii, 3, 115; i, 1, 36</ls>`
`<ls>Pāṇ. 5-2, 71</ls> (<s>°कीय</s> <lex type="phw">mfn.</lex>, <ls>iv, 2, 104 <ab>Vārtt.</ab> 30</ls>`
`<ls>Pāṇ. 5-3, 28</ls>) from the right or south, on the right side or southward from (<ab>gen.</ab>), <ls>RV.</ls> &c. (with √ <s>अस्</s> or <s>भू</s>, ‘to stand at the right side of. assist’, <ls>viii, 100, 2; x, 83, 7</ls>`
`<ls>Pāṇ. 5-3, 36</ls>), on the right side of or southward from (<ab>abl.</ab>: <ls>ii, 3, 29</ls>`
`<ls>Pāṇ. 5-3, 83</ls>; <ls>Kār.</ls>; <ls>Pat.</ls>]) of names so terminating (<s>यज्ञ-</s>, <s>देव-</s>, <s>जय</s> &c.) which chiefly are given to <s1 slp1="vESya">Vaiśya</s1> men, <ls>vi, 2, 148; v, 3, 78 ff.</ls>`
`<ls>Pāṇ. 5-4, 18</ls>; <ab>cf.</ab> <ls>viii, 3, 43</ls>`
`<ls>Pāṇ. 5-4, 18</ls>; in <ab>comp.</ab> before hard gutturals and labials <s>°तुः</s> or <s>°तुष्</s>, <ls>viii, 3, 43</ls>`
`<ls>Pāṇ. 6-1, 123 f.</ls>]) and <ab>ifc.</ab> ([<ls>v, 4, 92 and vi, 2, 72</ls>`
`<ls>Pāṇ. 6-1, 173</ls>; <ls>Kāś.</ls>; <ab>pf.</ab> <s>तुतो/द</s>; <ab>fut.</ab> 2nd <s>तोत्स्यति</s> or <s>तोत्ता</s>, <ls>vii, 2, 10</ls>`
`<ls>Pāṇ. 6-1, 196</ls> <ab>Sch.</ab>; 2. <ab>pl.</ab> <s>लुलुविध्वे</s> or <s>°विढ्वे</s>, <ls>ib. viii, 3, 79</ls>`
`<ls>Pāṇ. 6-2, 197</ls>) grown as old as to possess three teeth, <ls>v, 4, 141</ls>`
`<ls>Pāṇ. 6-2, 2</ls>) equal to, of the same kind or class or number or value, similar, comparable, like (with <ab>instr.</ab> or <ab>gen.</ab> [<ab>cf.</ab> <ls>ii., 3, 72</ls>`
`<ls>Pāṇ. 6-3, 17</ls> <ab>Sch.</ab>], <s>°ह्णे-तराम्</s> or <s>-तमाम्</s> [<ls>v, 4, 11</ls>`
`<ls>Pāṇ. 6-3, 34</ls> &c. (<s>-त्व</s> <lex type="phw">n.</lex>, <ls>vii, 3, 48</ls>`
`<ls>Pāṇ. 6-4, 100</ls>; <ab>fut.</ab> <s>भसिता</s>, vii, 2, 8 <ab>Vārtt.</ab> 1., <ls>Pat.</ls>;`
`<ls>Pāṇ. 6-4, 124</ls>; <ab>aor.</ab> <s>अजरत्</s> and <s>अजारीत्</s>, <ls>iii, 1, 38</ls>`
`<ls>Pāṇ. 6-4, 125</ls>; <ab>aor.</ab> <s>अफा<shortlong/>णीत्</s>, <ls>vii, 2, 27</ls>`
`<ls>Pāṇ. 6-4, 126</ls> <ab>Sch.</ab>; <ls>; 3</ls> <ab>pl.</ab> <s>दद्रुर्</s> or <s>ददरुर्</s>, <ls>vii, 4, 12</ls>`
`<ls>Pāṇ. 6-4, 4 f.</ls>]; <ab>ifc.</ab>, <ls>vii, 2, 99 f.</ls>`
`<ls>Pāṇ. 7-3, 33</ls>; <ls>Kāś.</ls>; <ab>Prec.</ab> <s>दासीष्ट</s>, <s>दायिस्°</s>, <ls>vi, 4, 62</ls>`
`<ls>Pāṇ. 6-4, 66</ls>], <ab>p.</ab> <s>धीय/मान</s>, <ls>RV. i, 155, 2</ls> <pb n="513,3"/>; <ab>aor.</ab> <s>अ/धायि</s>, <s>धा/यि</s>, <ls>RV.</ls> [<ls>Pāṇ. 7-3, 33</ls>; <ls>Kāś.</ls>]; <ab>Prec.</ab> <s>धासीष्ट</s> or <s>धायिषीष्ट</s> [<ls>vi, 4, 62</ls>`
`<ls>Pāṇ. 7-1, 59</ls>, <ab>Vārtt.</ab> 1, <ls>Pat.</ls>; <s>तृपति</s>, <ls>Dhātup.</ls>; <ab>pf.</ab> <ab>p.</ab> <ab>Ā.</ab> <s>तातृपाण/</s>, <ls>RV. x, 95, 16</ls>; <ab>P.</ab> <s>ततर्प</s>; 3. <ab>pl.</ab> <s>तातृपुर्</s>, <ls>AV. xi, 7, 13</ls>; <ab>aor.</ab> <s>अतृपत्</s>, <ls>iii, 13, 6</ls>`
`<ls>Pāṇ. 7-2, 10</ls>, <ab>Vārtt.</ab> 7, <ls>Pat.</ls>; <ab>pf.</ab> <s>डिड्ये</s>, <ls>viii, 4, 54</ls>`
`<ls>Pāṇ. 7-2, 2</ls>; <ab>pf.</ab> <ab>pl.</ab> <s>तत्सरुर्</s>, <ls>vi, 4, 120</ls>`
`<ls>Pāṇ. 7-2, 76</ls>; 3. <ab>pl.</ab> <s>°क्षति</s>, <ls>vi, 1, 6 and 189; vii, 1, 4</ls>`
`<ls>Pāṇ. 7-2, 99</ls>, <ab>Vārtt.</ab> 2]; <ab>instr.</ab> <s>चतसृ/भिस्</s> [<ab>cf.</ab> <ls>vi, 1, 180 f.</ls>`
`<ls>Pāṇ. 7-2, 9</ls>; <ls>Kāś.</ls>) a loom, <ls>v, 2, 70</ls>`
`<ls>Pāṇ. 8-1, 47</ls>; in connection with the <ab>Pot.</ab> and <s>ना<srs/>वकल्पयामि</s> &c. (<ls>iii, 3, 147</ls>`
`<ls>Pāṇ. 8-2, 2</ls> <ab>Intens.</ab> <s>जेगिल्यते</s>, <ls>iii, 1, 24</ls>`
`<ls>Pāṇ. 8-3, 10</ls>] <ab>instr.</ab> <s>नृ/भिस्</s>, or <s>नृभि/स्</s>; <ab>dat.</ab> <ab>abl.</ab> <s>नृ/भ्यस्</s> or <s>नृभ्य/स्</s> <ab>loc.</ab> <s>नृ/षु</s> or <s>नृषु/</s> [<ls>vi, 1, 184</ls>`
`<ls>Pāṇ. 8-3, 78</ls> <ab>Sch.</ab>; <ab>Prec.</ab> <s>प्लोषीष्ट</s>, <ls>vii, 2, 43</ls>`
`<ls>Pāṇ. 8-4, 19</ls> <ab>Sch.</ab>; <ab>impf.</ab> <s>प्रा<srs/>णत्</s>, <ls>vii, 3, 99</ls>`

Hope @funderburkjim would consider [the same way he was responding to many of my suggestions all these days] reverting all the Indo-Arabic numbers at the Pāṇ. references to Roman numbers to match with the book and the "theme" of MW.
**[I would again reiterate that we have no right to change the book content this way, for whatever reason.]**

And having the Roman numbers does not in anyway be a hurdle in cross-referencing to another external source, which is the way RV references are linked.
**[I still am wondering why and how this erratic correction took place in MW text.]**
`-------------`
Alternatively,  now that I gave the instances where the correction is "missed" so far, probably they could be changed to IA numbers, so that the change is **complete** throughout the text!!
**[And this would be my last post in the forum.]**

**Comment by gasyoun** [comment]
> There is no semi-colon between RV. and Prāt. in the print

Interesting point.

> [And this would be my last post in the forum.]

You meant in the thread, @Andhrabharati ?

**Comment by funderburkjim** [comment]
Note that we now have links for the Panini references in mw, for instance the link in nirRane (slp1) to https://ashtadhyayi.com/sutraani/6/2/178.

The php code which dynamically generates these links would need to be changed at the same time as a change in the mw.txt text for the Panini references.

There is so much to do.  Currently, I have a local list of 158  Github TODO issues, and this issue #519 is in the list.

**Comment by Andhrabharati** [comment]
Good to see this going into your TODO list, @funderburkjim!

And which is the way you opted for, the first one or the alternative?

**Comment by gasyoun** [comment]
> local list of 158 Github TODO issues

Can you share it, please?

**Comment by Andhrabharati** [comment]
Just made a listing of open issues at the 58 repos-
[CDSL repos and open issues.txt](https://github.com/sanskrit-lexicon/csl-orig/files/7271548/CDSL.repos.and.open.issues.txt)

Out of these 16 repos have no open issues.

Rest of the repos counted a total of 677 (as of now).
Seen that COLOGNE count (153) is close to 158 that @funderburkjim had mentioned; could it be the one he intended?

If he hasn't prioritised the sequence of handling the TODO list, I wish my current issue getting its turn a little earlier!!

**Comment by gasyoun** [comment]
> If he hasn't prioritised the sequence of handling the TODO list, I wish my current issue getting its turn a little earlier

@funderburkjim what's on the priority list? Seems @Andhrabharati deserves to be higher in the list, thanks to you both.

**Comment by funderburkjim** [comment]
> TO GET BOTH LINKS, change to two LS tags. Notice that 'Pāṇ.' appears twice
`<ls>Pāṇ. 6-2, 178</ls>; <ls>Pāṇ. 8-4, 5</ls>;`
Do we want to make this print change?
No, please don't correct the print matter thus.
Instead you can mark them as `<ls n="RV."> as done in PWG to get a different link.

Just tried the 'n=' idea and confirmed that display logic for MW handles this similarly to the way PWG handles.
`<ls>Pāṇ. 6-2, 178</ls>; <ls n="Pāṇ.">8-4, 5</ls>`  Notice the display now has 2 parts:
![image](https://user-images.githubusercontent.com/6393033/136071095-cacc371d-3284-43e9-8707-3091c92d3357.png)

Will go through the list in [the comment above](https://github.com/sanskrit-lexicon/csl-orig/issues/519#issuecomment-922466781).

**Comment by Andhrabharati** [comment]
> Good to see this going into your TODO list, @funderburkjim!
> 
> And which is the way you opted for, the first one or the alternative?

I got the answer, and this issue has served the intended purpose, @drdhaval2785!

**Comment by drdhaval2785** [comment]
Close.

**Comment by gasyoun** [comment]
`Vārtt. 5` missing in MW

![vart](https://github.com/sanskrit-lexicon/csl-orig/assets/80761/ea04748f-c2e5-416f-a2a3-98de17a92fc2)

**Comment by funderburkjim** [comment]
> Vārtt. 5 missing in MW

There is a tooltip for 'Vārtt.'  (The tooltip is 'Vārttika')
In CDSL, `Vārtt.' is just marked as an abbreviation:  `<ab>Vārtt.</ab> 5`
CDSL does not have any link target for `Vārtt,'  

There IS a link target for The Panini reference:  https://ashtadhyayi.com/sutraani/2/3/69

In this is a commentary section labeled महाभाष्यम्.   
Question   Does 'Vārtt. 5' refer to some text present in the महाभाष्यम्  section?

**Comment by Andhrabharati** [comment]
शानंश्चानश्शतॄणामुपसंख्यानम् is the Vartt. 5 and the following
(भाष्यम्) शानश्चानश्शतॄणामुपसंख्यानं कर्तव्यम्। सोमं पवमानः। नटमाघ्नानः। अधीयन्पारायणम्। लप्रयोगे नेति निषेधो न प्राप्नोति ॥ (वार्तिकवैर्यथ्यभाष्यम्) मा भूदेवम्। तृन्नित्येवं भविष्यति ॥ कथम्?। तृन्निति नेदं प्रत्ययग्रहणम् ॥ किं तर्हि? प्रत्याहार ग्रहणम् ॥ क्व संनिविष्टानां प्रत्याहार?। लटश्शतृ - इत्यतः प्रभृत्या तृनो नकारात् ॥ (आक्षेपभाष्यम्) यदि प्रत्याहारग्रहणम्, चोरस्य द्विषन् अत्रापि प्राप्नोति ॥ is the Patanjali's Mahābhāṣya

![image](https://github.com/sanskrit-lexicon/csl-orig/assets/75209130/e3c7397b-3278-444c-8412-4f03aeb8616f)

**Comment by Andhrabharati** [comment]
Varttika is the textual correction(s)/amendment(s) to Pāṇini by Kātyāyana, and Patanjali has rendered his Mahābhāṣya on both Pāṇini's original Sūtras and Kātyāyana's Varttikas together.

**Comment by funderburkjim** [comment]
OK.  So the reason Vartt. 5 appears in MW reference under headword 'dvizat'  is because of the 
mention of 'dvizan' 

<img width="593" alt="image" src="https://github.com/sanskrit-lexicon/csl-orig/assets/6393033/bcb5df7b-7e58-4b81-b0fd-f4fc90ec2602">
 
Right?

**Comment by Andhrabharati** [comment]
Right.
