### ISSUE TITLE
ap90 ls markup consistency with ap57

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-orig#527]
In comparing the literary source abbreviations used by ap90 and ap57, a few 
differences were noted.  
Changes were made to the ap90 abbreviations to resolve these differences:
```
Taitt. Up. -> T. Up.  (6)
Cand. M. -> Chand. M. (4)
Subhāsh. -> Subhāṣ. (187)
Sāṃkhya K. -> Sāṅ. K. (5)
Sān. K. -> Sāṅ. K. (14)
Sar. S. ->  Sarva. S. (3)
Sarva. -> Sarva. S. (1?)
Sān. S. -> Sāṅ. S. (1)
Gaut. Sūt. -> Gaut. S. (2)
Dāy. -> Dāy. B. (1)
Śukra N. -> Śukra (1)
Upan. -> Up. (1)
```

Changes also were made to the ap90 abbreviation tooltips.

**Comment by gasyoun** [comment]
> Changes were made to the ap90 abbreviations to resolve these differences

What a wanted work!

**Comment by Andhrabharati** [comment]
I would've suggested such ones to be marked as alt. forms.

Many such are in PWG, VCP, PWK, AP90, ... in the references.

The normalistaion/unification could be done internally, not while displaying to the public; otherwise it amounts to making the work a revised edition, which Jim himself has mentioned earlier (saying he is against doing so).
