### ISSUE TITLE
semantic versioning proposal

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#6]
Now we have agreed in principle to work on a git based work flow for the csl-orig data and generate the dictionaries therefrom.
Now it is more imperative for us to specify the version number of a particular .txt / .xml file.
I propose we use the semantic versioning 2.0.0 as mentioned at https://semver.org/

# Crux

1. Format is MajorVersion.MinorVersion.Patch e.g. 1.1.25
2. Whenever only a minor correction is made e.g. a typo, bump the Patch e.g. 1.1.26
3. Whenever a generic change is incorporated e.g. markup of abbreviations made, bump the MinorVersion and reset Patch to 0 e.g. 1.2.0
4. Whenever there is backward incompatible change e.g. Metaline-IAST change etc, bump the MajorVersion and reset both MinorVersion and Patch to 0 e.g. 2.0.0.

make_xml.py will need to take these changes from .txt to  .xml file.

@funderburkjim, @gasyoun  and @YevgenJohn What is your take on this?

**Comment by YevgenJohn** [comment]
I wonder if we could have those versions (snapshot of stable configuration in time) as branches in all relevant csl-* repos, so the installer's job is easy by mere cloning the right branch from each projects involved. We can have master branch to hold the latest approved state, while personal branches as sandbox for the problems we're fixing (which we will sent pull request from and delete upon merging to the master branch), but the version branches are freezing at the time we cut that version off, so further references to it will pull the known stable configuration. My two cents, and I'm with whichever versioning model seems the most reasonable for the team (I'm too new to process to understand all pitfalls), even Linux kernel changed its numbering model over time, so, I guess, there's no one single answer to that, so we might try different approaches over time, but, since version is mere branch label, its content is irrelevant to the branching approach to freeze snapshots in time using Git technologies. Thank you!

**Comment by funderburkjim** [comment]
@drdhaval2785  Semantic versioning ok in principle.  Please go ahead and do what is needed to put the idea into practice, and disseminate instructions and examples so others can know how to be in compliance with the versioning.

My first impression is that I don't like the idea of proliferating branches.  It sounds like this would result in a hopeless tangle of branches.   

Rather, we should strive to make sure the latest versions of the repositories are stable and compatible.  *Compatible* means, for instance, that a change in markup in csl-orig might need to be coordinated with a change in basicdisplay.php of csl-websanlexicon, or a change in make_xml.py or one.dtd of csl-pywork).

**Comment by gasyoun** [comment]
> If this seems good, let us start mentioning 1.0.0 to the version of .txt and .xml file as it exists on 31 Oct 2019.

It sure does.

> We can have master branch to hold the latest approved state, while personal branches as sandbox for the problems we're fixing

Agree.

> Temporary branches, as a way to test changes before committing them to master, seem useful.

Exactly.  Now that most of the code is open, we can play. Is most of the code open, @funderburkjim ?

**Comment by funderburkjim** [comment]
AFAIK, most of the code is open.  

We've got good pieces of documentation scattered in various places, regarding how all the repositories fit together for usage.  But we need to have some 'go to' place for the documentation.
When we have documentation in one place, then we can better identify, and then fill, gaps.

I suggest that this primary location for documentation be prepared by others, probably headed by @drdhaval2785.   I will of course add clarifications as needed, but if others assume documentation responsibility, then it will not be 'Jim-centric'.

**Comment by gasyoun** [comment]
> When we have documentation in one place, then we can better identify, and then fill, gaps.

Yes, as the case with @YevgenJohn showed it is not so much the absence of the documentation, but how much scattered it is around. Let it be non 'Jim-centric'. @drdhaval2785 let's have a call to understand where we want to go next and if we have reached what we spoke about in August?

**Comment by drdhaval2785** [comment]
@gasyoun I can vouch that the documentation is not at all Jim centric now. With the present workflow and instructions, both @YevgenJohn and I were able to install dictionaries on two different local machines i.e ubuntu and centOS, without much hassle. A sizeable progress.

Will work on documentation once the work stabilizes. Currently @funderburkjim is making fast improvements and changes. Documentation made will be obsolete within a week.

**Comment by drdhaval2785** [comment]
We follow semantic versioning now at CDSL.
